version: '3.5'

services:
    example-backend:
        image: example-backend
        ports: 
            - 8080:8080
    example-frontend:
        image: example-frontend
        ports:
            - 5000:5000
        