version: '3.5'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy-network
    ports: 
      - 80:80

  example-frontend:
    image: example-frontend
    ports:
        - 5000:5000
    networks:
      - proxy-network

  example-backend:
    image: example-backend
    ports: 
        - 8080:8080
    environment: 
        - REDIS_HOST=redis-cache
        - POSTGRES_HOST=postgres-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=dowd2021
        - POSTGRES_DATABASE=postgres
    networks:
      - proxy-network
      - db-network

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    networks:
      - db-network

  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=dowd2021
    volumes:
      - database:/var/lib/postresql/data
    networks:
      - db-network
    

volumes:
  database:

networks: 
  proxy-network:
    name: proxy-network
  db-network:
    name: db-network