FROM node:14-alpine
WORKDIR /app
EXPOSE 5000
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
COPY . ./
ENV REACT_APP_BACKEND_URL=http://localhost/api
RUN npm run build
RUN npm install -g serve

RUN addgroup -g 1001 frontend
RUN adduser -u 1001 -G frontend -h /home/username -D frontend
RUN chown -R frontend:frontend build

USER frontend

CMD ["serve",  "-s", "-l", "5000", "build"]