version: '3.5'

services:
  redis-cache:
    image: redis:latest
    container_name: redis-cache
  example-backend:
    image: example-backend
    ports: 
        - 8080:8080
    environment: 
        - REDIS_HOST=redis-cache
        - POSTGRES_HOST=postgres-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=dowd2021
        - POSTGRES_DATABASE=postgres
  example-frontend:
    image: example-frontend
    ports:
        - 5000:5000
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=dowd2021
    volumes:
      - database:/var/lib/postresql/data

volumes:
  database:
