version: '3.5'

services:
    redis-cache:
        image: redis:latest
        container_name: redis-cache
    example-backend:
        image: example-backend
        ports: 
            - 8080:8080
        environment: 
            - REDIS_HOST=redis-cache
    example-frontend:
        image: example-frontend
        ports:
            - 5000:5000