version: '3.5'
services:
  training:
    image: ml-kurkkumopo-training
    volumes: 
      - model:/src/model
      - images:/src/imgs
  backend:
    image: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  frontend:
    image: ml-kurkkumopo-frontend
    ports:
      - 3000:3000
volumes:
  model:
  images:
